name: Bump version.txt file on pull request to main
on:
  pull_request:
    branches:
      - "main"
    types: [opened]

jobs:
  bump_version_txt:
    name: Bump version.txt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@master
        with:
          ref: main

      - name: Get version.txt contents on main
        shell: bash
        run: |
         echo "::set-output name=OLD_VERSION::$(cat "version.txt")"
        id: old_version

      - name: Checkout feature branch
        uses: actions/checkout@master

      - name: Get version.txt contents on feature branch
        shell: bash
        run: |
          echo "::set-output name=NEW_VERSION::$(cat "version.txt")"
        id: new_version

      - name: Bump version.txt (if necessary)
        if: ${{ steps.old_version.outputs.OLD_VERSION == steps.new_version.outputs.NEW_VERSION }}
        shell: bash
        run: |
          versionBump=$(echo ${{ steps.new_version.outputs.NEW_VERSION }} | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g')
          echo $versionBump > version.txt

      - name: Update PR (if necessary)
        if: ${{ steps.old_version.outputs.OLD_VERSION == steps.new_version.outputs.NEW_VERSION }}
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Auto-bumping version.txt